on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  t:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh release delete -y master-nightly || :
          git push --force origin HEAD:refs/tags/master-nightly
          gh release create --verify-tag -p --generate-notes master-nightly "README.md"
