on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git push --force origin HEAD:refs/tags/master-nightly
